[[Install]]
== Installation


You can either download a prebuilt jar from the https://github.com/jbarrasa/neosemantics/releases[releases area] or build it from the source. If you prefer to build, check the note below.

1. Copy the  the jar(s) in the <NEO_HOME>/plugins directory of your Neo4j instance. (**note:** If you're going to use the JSON-LD serialisation format for RDF, you'll need to include also https://neo4j-contrib.github.io/neo4j-apoc-procedures/[APOC])
2. Add the following line to your <NEO_HOME>/conf/neo4j.conf (notice that it is possible to modify where the extension is mounted by using an alternative name to `/rdf` below).
[source,shell]
----
dbms.unmanaged_extension_classes=semantics.extension=/rdf
----
3. Restart the server. 
4. Check that the installation went well by running 
[source,cypher]
call dbms.procedures() 

The list of procedures should include the ones documented below.
You can check that the extension is mounted by running 
[source,cypher]
:GET /rdf/ping



**Note on build**

When you run
[source,shell]
  mvn clean package

it will produce two jars

1. A neosemantics-[...].jar This jar bundles all the dependencies.
2. An original-neosemantics-[...].jar This jar is just the neosemantics bit. So go this way if you want to keep the third party jars separate. In this case you will have to add all third party dependencies (look at the pom.xml). 
  

=== Feedback
Please provide feedback and report bugs as GitHub issues or join the Neo4j Community Forum.

=== Acknowledgements
NSMNTX uses https://rdf4j.eclipse.org/[rdf4j] for parsing and serialising RDF. Eclipse rdf4j is a powerful Java framework for processing and handling RDF data.

The following functionalities have been developed by https://github.com/ArkanEmre[Emre Arkan] in the context of his bachelor thesis in cooperation with https://www.eccenca.com/en/index.html[eccenca GmbH] and https://www.th-brandenburg.de[Brandenburg University of Applied Sciences]:

* Import (<<ImportQuadRDF>>) and Export of Quadruples
* Preservation of custom data types (<<CustomDataTypes>>)
* Deletion of formerly imported RDF data (<<DeleteRDF>>)

