= Installation
:page-pagination:


You can either download a prebuilt jar from the https://github.com/jbarrasa/neosemantics/releases[releases area] or build it from the source. If you prefer to build, check the note below.

1. Copy the jar(s) in the <NEO_HOME>/plugins directory of your Neo4j instance. (**note:** If you're going to use the JSON-LD serialisation format for RDF, you'll need to include also link:/labs/apoc/[APOC])
2. Add the following line to your <NEO_HOME>/conf/neo4j.conf (notice that it is possible to modify where the extension is mounted by using an alternative name to `/rdf` below).
+
[source,shell]
----
server.unmanaged_extension_classes=n10s.endpoint=/rdf
----
+
[NOTE]
----
When the property `dbms.security.procedures.allowlist` is set, then it must include `n10s.*`` too.
----
3. Restart the server.
4. Check that the installation went well by running
[source,cypher]
SHOW PROCEDURES WHERE name STARTS WITH "n10s"

The list of procedures should include the ones documented below.
You can check that the extension is mounted by running
[source,cypher]
----
:GET http://localhost:7474/rdf/ping
----
The previous command assumes you're running neo4j on your local machine, replace `localhost` with the host name if that is not the case.

**Note on build**

When you run
[source,shell]
  mvn clean package

it will produce two jars

1. A neosemantics-[...].jar This jar bundles all the dependencies.
2. An original-neosemantics-[...].jar This jar is just the neosemantics bit. So go this way if you want to keep the third party jars separate. In this case you will have to add all third party dependencies (look at the pom.xml).


== Feedback
Please provide feedback and report bugs as https://github.com/jbarrasa/neosemantics/issues[GitHub issues] or join the https://community.neo4j.com/[Neo4j Community] forum.

== Acknowledgements
Neosemantics uses https://rdf4j.eclipse.org/[rdf4j] for parsing and serialising RDF. Eclipse rdf4j is a powerful Java framework for processing and handling RDF data.
